### ISSUE TITLE
Google Chrome: Executing JavaScript through AppleScript is no longer supported

### ISSUE THREAD

**Issue by oschrenk** [thalesmello/webcomplete.vim#3]
A heads up: I'm running Google Chrome 59.0.3053.3 and today i started to get error messages for webcomplete.vim:

```
 [deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/oschrenk/.tilde/dotfiles/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 124, in g
ather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/Users/oschrenk/.config/nvim/plugged/webcomplete.vim/rplugin/python3/deoplete/sources/webcomplete.py", line 43, in gathe
r_candidates
[deoplete]     stdoutdata, _ = self.__process.communicate()
[deoplete]   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 823, in comm
unicate
[deoplete]     stdout = self.stdout.read()
[deoplete] ValueError: read of closed file
[deoplete] Could not get completions from: webcomplete.  Use :messages for error details.
```

Running `~/.config/nvim/plugged/webcomplete.vim/sh/webcomplete` I get this sad message:

```
67:87: execution error: Google Chrome got an error: Executing JavaScript through AppleScript is no longer supported. (12)
```

**Comment by oschrenk** [comment]
I pushed a version based on https://github.com/thalesmello/webcomplete.vim/issues/1#issuecomment-257049031
to https://github.com/oschrenk/webcomplete.vim and using the remote debugging protocol

Unfortunately, it's not working reliably. Sometimes I just get empty results back. It has something to do with the Remote Debugging Protocol and Chrome not reliably returning the frontmost tab (but some other activity). Still trying to figure out why that is.

**Comment by thalesmello** [comment]
I've been thinking about this issue recently. Maybe one way we could use to
solve this problem could be to write a companion Chrome extension that
write the contents of the page everytime the page is focused. Vim could
them access the contents of the file. I haven't had the chance do this yet,
but there should be no problem implementing that.

**Comment by oschrenk** [comment]
I'm looking into your suggestion of writing a Chrome extension since Chrome doesn't have an option 
to always start in debug mode and I tend to forget to start it that way.

But already early on I run into

```
Warning
`fileSystem' is only allowed for packaged apps, but this is a extension.
Warning
'fileSystem.write' is only allowed for packaged apps, but this is a extension
```

Unfortunately, Chrome doesn't allow extensions to write to the filesystem, 
see https://bugs.chromium.org/p/chromium/issues/detail?id=176741, so the idea of having the content of a tab written out to disk doesn't work. These people had the [same-ish issue](https://github.com/Wykks/Untamed-Now-Playing-Next/issues/93). The issue mentions another [project](https://github.com/pendo324/EssentialNowPlaying) which solved the problem by writing a native app, with which they communicate. I don't want to do that.

Looking into other options of getting content written to disk.

**Comment by thalesmello** [comment]
Thanks for the update @oschrenk .

It looks like native extensions would be the only viable alternative to make the plugin work again.

I'm thinking about writing the native extension in Node, as [there is a library](https://www.npmjs.com/package/chrome-native-messaging) for writing chrome host programs, and it's also possible to package it using [pkg](https://github.com/zeit/pkg).

Even though it's more complicated, the upside is the native messaging protocol is mostly [compatible with Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging), so that would make the process of supporting Firefox straightforward.

Any thoughts about this strategy?

**Comment by oschrenk** [comment]
While you commented, I wasted some time having the extension write to LocalStorage in the background page of the extension. That writes to a leveldb in `/Users/<user-id>/Library/Application Support/Google/Chrome/Default/Local Extension Settings/<extension-id>` but I wasn't able to concurrently read from it yet. It would then at least need a leveldb client to be installed by the user.

Native Messaging and some simple host app actually seems the way to go.

**Comment by zhuangya** [comment]
now, Chrome 61.0.3163.100 can run javascript from osascript 🎆 

![image](https://user-images.githubusercontent.com/499038/31423983-6b1f4030-ae1d-11e7-978b-89d078efeadd.png)

**Comment by oschrenk** [comment]
I guess they reverted their decision and now support it again.

@zhuangya Thanks for retrying!

Edit:
Also works again on Chrome 62.0.3202.4

**Comment by oschrenk** [comment]
Hopefully Google keeps it that way. 

@thalesmello You can close the issue if you want.
